apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "beaverdeck.suppressedInsightsConfigMapName" . }}
  namespace: {{ include "beaverdeck.namespace" . }}
  labels:
    {{- include "beaverdeck.labels" . | nindent 4 }}
    app.kubernetes.io/component: insights
data:
  {{ .Values.suppressedInsights.key | quote }}: "[]"
