nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

image:
  repository: arequs/beaverdeck
  tag: 1.5.1
  pullPolicy: IfNotPresent

listenAddr: ":8080"
dataDir: /data
clusterName: "Cluster name not set"
managedNamespace: ""
allowAllNamespaces: true

suppressedInsights:
  configMapName: ""
  key: suppressed_insights.json

podAnnotations: {}
podLabels: {}

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true
  clusterRoleName: ""

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClass: default

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations: {}

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 10
  periodSeconds: 20

readinessProbe:
  enabled: true
  path: /healthz
  initialDelaySeconds: 5
  periodSeconds: 10

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /
  pathType: Prefix
  tls: []

extraEnv: []
